name: GH-Actions-Satellites

on:
  workflow_dispatch:
    inputs:
      branch:
        type: "string"
        default: "main"
jobs:
  satellites-build:
    runs-on: arc-runner-set
#    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.15
      - uses: actions/checkout@v3
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: List Environments
        run: |
          printenv
          whoami
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Earthly version
        run: earthly --version
      - name: Run CI pipeline
        run: "earthly --push --no-cache +main"
